#!/usr/bin/bash

# Save current working directory
WORKING_DIR=$(pwd)

# Change directory to SASTBenchmark directory
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )"

# Setup SASTBenchmark if not done yet
if [ ! -d ".venv" ]; then
    uv sync
fi

# Run CLI from SASTBenchmark directory
WORKING_DIR="$WORKING_DIR" .venv/bin/python3 main.py "$@"