name: Run tests on Pull Request

on:
  pull_request:
      branches:
        - 'main'
      paths: 
        - 'codesectools/**'
        - 'tests/**'
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: make test